version: 2
updates:
  - package-ecosystem: "cargo"
    # Directory where to search for build system configuration
    directory: "/" 

    # increase: Always increase the minimum version requirement to match the new version. If a range already exists, typically this only increases the lower bound.
    # increase-if-necessary"	Leave the constraint if the original constraint allows the new version, otherwise, bump the constraint.
    # lockfile-only"	Only create pull requests to update lockfiles. Ignore any new versions that would require package manifest changes.
    # widen"	Widen the allowed version requirements to include both the new and old versions, when possible. Typically, this only increases the maximum allowed version requirement.
    versioning-strategy: "auto"
    
    # Check for updates weekly.
    # This makes sure dependabot doesn't open PRs too often.
    schedule:
      interval: "daily"
    
    # Group dependencies, so dependabot does not open a million pull requests and instead just
    # makes "bump everything" every once in a while
    groups:
      lock:
        patterns: ["*"]

    # Allow both direct and indirect updates for all packages
    allow:
      - dependency-type: "all"
    
    # Which labels to apply
    labels: ["A-dependencies"]

    target-branch: "dev"

    # Stop dependabot from updating dependencies when the previous dependabot PR hasn't been
    # merged/closed yet
    open-pull-requests-limit: 1