name: Shuttle Deploy
description: Deploy to Shuttle

on:
  push:
    branches:
      - main
  workflow_dispatch:

  jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: CleverWild/untis_telegram_bot@main
        with:
          shuttle-api-key: ${{ secrets.SHUTTLE_API_KEY }}
          project-id: proj_01JD7TEVDTTF6WTAAD37MWSCSV
