[package]
edition = "2021"
name = "untis"
version = "0.3.2"

[dependencies]
thiserror = "2.0.12"
tracing = "0.1.41"

[dependencies.chrono]
version = "0.4"

[dependencies.reqwest]
version = "0.12"
features = [
    "cookies",
    "json",
    "hickory-dns",
]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.serde_json]
version = "1.0"

[dependencies.rand]
version = "0.9.1"
