[package]
edition = "2021"
name = "untis"
version = "0.3.2"

[dependencies]
# Зависимости теперь наследуются из workspace
chrono = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
