name: Auto PR from dev to prod

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch prod branch
        run: git fetch origin prod

      - name: Get version from dev branch
        id: dev_version
        run: |
          DEV_VERSION=$(grep '^version = ' Cargo.toml | sed 's/version = "\(.*\)"/\1/')
          echo "version=$DEV_VERSION" >> $GITHUB_OUTPUT

      - name: Get version from prod branch
        id: prod_version
        run: |
          PROD_VERSION=$(git show origin/prod:Cargo.toml | grep '^version = ' | sed 's/version = "\(.*\)"/\1/')
          echo "version=$PROD_VERSION" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: ${{ steps.dev_version.outputs.version > steps.prod_version.outputs.version }}
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: auto-pr-from-dev-to-prod
          base: prod
          title: "Auto PR from dev to prod"
          body: |
            This PR is automatically created to update the prod branch with changes from dev, 
            because new version ${{ steps.dev_version.outputs.version }} is available.