name: Shuttle Deploy

on:
  push:
    branches: [ "prod" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          shuttle-api-key: ${{ secrets.SHUTTLE_API_KEY }}
          project-id: proj_01JD7TEVDTTF6WTAAD37MWSCSV
